Add Romanian translation and fix English strings
Twilight0/plugin.program.yt-setup pull request #2
Opened 2020-04-03 17:52 UTC by tmihai20

Added Romanian Translation and fixed English strings

2020-04-03 17:58 UTC, Twilight0 requested changes

2020-04-03 17:58 UTC, Twilight0 commented on resources/language/resource.language.en_gb/strings.po
> +msgid "Execute setup wizard"
I would like this to remain as it was.

2020-04-04 10:29 UTC, Twilight0 commented
Thank you very much, I cherrypicked your commit regarding the romanian translation, so in a sense this PR has been merged.

2020-04-04 10:29 UTC, closed without merging

2020-04-04 10:39 UTC, tmihai20 commented
Ok then, I will have to update my Romanian translation. You still have a typo inside the English strings, it had **el** instead of **en**.

2020-04-04 10:40 UTC, Twilight0 commented
I fixed it myself, thank you for your contribution once again.